---
- name: Distribute SSH public keys
  hosts: all
  gather_facts: false
  become: yes
  become_method: sudo  # Explicitly set sudo
  become_user: root  # Run as root

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Copy public SSH key to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '/home/nick/.ssh/ansible_automation_key.pub') }}"
